site_name: 'Baqend Guide'
site_favicon: 'img/favicon.ico'
site_url: 'https://www.baqend.com/guide'
repo_url: 'https://github.com/Baqend/guide'
pages:
    - Quickstart: 'gettingstarted/index.md'
    - Guide:
        - 'Home': 'index.md'

        - 'Overview': 'topics/overview/index.md'
        - 'Dashboard': 'topics/dashboard/index.md'
        - 'CLI': 'topics/cli/index.md'

        - 'Setup': 'topics/setup/index.md'
        - 'CRUD': 'topics/crud/index.md'
        - 'Schema and Types': 'topics/schema/index.md'
        - 'Queries': 'topics/queries/index.md'
        - 'Real-Time Queries': 'topics/realtime/index.md'
        - 'User Management': 'topics/user-management/index.md'
        - 'Baqend Code': 'topics/baqend-code/index.md'
        - 'Push Notifications': 'topics/push/index.md'
        - 'Deep Loading': 'topics/deep-loading/index.md'
        - 'Hosting': 'topics/hosting/index.md'
        - 'Files': 'topics/files/index.md'
        - 'Caching': 'topics/caching/index.md'
        - 'Logging': 'topics/logging/index.md'

    - Starter Kits: 'starters.md'
    - Roadmap: 'roadmap.md'
docs_dir: src
site_dir: docs
theme_dir: theme
markdown_extensions: [fenced_code]
#theme: cosmo
