site_name: 'Baqend Guide'
site_favicon: 'img/favicon.ico'
site_url: 'https://www.baqend.com/guide'
repo_url: 'https://github.com/Baqend/guide'
pages:
    - Quickstart: 'gettingstarted.md'
    - Guide:
        - 'Home': 'index.md'

        - 'Overview': 'topics/overview.md'
        - 'Dashboard': 'topics/dashboard.md'
        - 'CLI': 'topics/cli.md'

        - 'Setup': 'topics/setup.md'
        - 'CRUD': 'topics/crud.md'
        - 'Schema and Types': 'topics/schema.md'
        - 'Queries': 'topics/queries.md'
        - 'Real-Time Queries': 'topics/realtime.md'
        - 'User Management': 'topics/user-management.md'
        - 'Baqend Code': 'topics/baqend-code.md'
        - 'Push Notifications': 'topics/push.md'
        - 'Deep Loading': 'topics/deep-loading.md'
        - 'Hosting': 'topics/hosting.md'
        - 'Files': 'topics/files.md'
        - 'Caching': 'topics/caching.md'
        - 'Logging': 'topics/logging.md'

    - Starter Kits: 'starters.md'
    - Roadmap: 'roadmap.md'
docs_dir: src
site_dir: docs
theme_dir: theme
markdown_extensions: [fenced_code]
#theme: cosmo
