site_name: Baqend Guide
site_favicon: '/img/favicon.ico'
site_url: 'http://www.baqend.com'
pages:
- [index.md, JavaScript Guide]
docs_dir: src
site_dir: docs
theme_dir: theme
markdown_extensions: [fenced_code]
#theme: cosmo
